### ISSUE TITLE
Doppeltes Peering kann nicht mehr gelöscht werden

### ISSUE THREAD

**Issue by ThorstenPferdekaemper** [kc-GitHub/FHEM-HM485#12]
Irgendwie ist es möglich, einen Sensor-Kanal zweimal mit demselben Aktor-Kanal zu peeren. In dem Fall scheint es nicht mehr möglich zu sein, das Peering zu löschen oder irgendwie zu bearbeiten.

**Comment by ThorstenPferdekaemper** [comment]
Hier sind ein paar Screenshots dazu:
![uebersicht](https://cloud.githubusercontent.com/assets/7566477/9174487/71380a32-3f80-11e5-9970-1f53b7db5faf.jpg)
![channel 2](https://cloud.githubusercontent.com/assets/7566477/9174488/730d6618-3f80-11e5-956b-e44942b07e2a.jpg)
![channel 1](https://cloud.githubusercontent.com/assets/7566477/9174489/745556d4-3f80-11e5-9b1f-dc0f13f873c9.jpg)

**Comment by hresalg** [comment]
Hallo
Das ging, wenn man dei Seite nicht aktualisiert hat. Nun sollte man nicht mehr 2 gleiche peers anlegen können. Ich schreibe jetzt die eeprom Werte direkt ins Reading, somit aktualisiert das "set" ohne das ACK vom Device abzuwarten.
lg Harald

**Comment by ThorstenPferdekaemper** [comment]
Hi,
doch, es geht noch. Es erscheinen nur keine gepeerten Kanäle mehr in der Drop-Down-Box. Man kann aber in der Kommandozeile sehr wohl noch doppelt peeren.
Man kann sogar in der Kommandozeile das eingeben: 
            "set HMW_LC_Bl1_DR_MEQ0078948_01 peer muell"
Das geht ohne Fehlermeldung durch. Im Device steht dann 
            " peer_act_0   channel_01 → unknown"
Irgendwas wird auch ans Device geschickt. Das Peering kann man dann nicht mehr löschen. 
Also drei Probleme:
1. Man kann schon gepeerte Kanäle nochmal peeren.
2. Man kann totalen Müll peeren.
3. Man kann Müll-Peerings nicht mehr löschen.
Gruß,
   Thorsten

**Comment by hresalg** [comment]
1. Man kann schon gepeerte Kanäle nochmal peeren.
sollte nun nicht mehr gehen
2. Man kann totalen Müll peeren.
Das wird nun abgefangen
3. Man kann Müll-Peerings nicht mehr löschen.
Naja fehlt noch sollte es aber nicht geben.
lg Harald

**Comment by ThorstenPferdekaemper** [comment]
Das ist wahrscheinlich gefixt, muss aber noch getestet werden.

**Comment by ThorstenPferdekaemper** [comment]
Folgendes macht immer noch Probleme: Peering zu Device (vielleicht auch mehrere), dann Device löschen. Peerings löschen geht dann manchmal nicht.

**Comment by ThorstenPferdekaemper** [comment]
Problem war nicht mehr nachvollziehbar

**Comment by ThorstenPferdekaemper** [comment]
Moved to master
