### ISSUE TITLE
Falsche EEPROM-Adressen bei Parametern > 1 Byte

### ISSUE THREAD

**Issue by Markus0** [kc-GitHub/FHEM-HM485#6]
Bei HM485-Geräten mit Parametern mit einer Größe > 1 Byte kann es zu einer fehlerhaften Berechnung der EEPROM-Adresse kommen.
In Modul Device.pm steht in der Funktion "getPhysical" die folgende Zeile:
$adrId       = $adrId + ($chId * $adressStep * ceil($size));
Der Ausdruck "ceil($size)" kann vermutlich entfallen, da er bei einer Größe <= 1Byte keine Auswirkung hat und bei Größen > 1Byte dazu führt, dass der komplette adressStep (also die Größe für alle Parameter) bei der Berechnung der Adresse mehrfach berücksichtigt wird.

Ich habe bisher kein original HM485-Gerät gefunden, bei dem dieses Problem relevant ist. Entweder gibt es bei den Geräten keine Parameter, die größer als 1 Byte sind, oder wie z.B. beim HMW-LC-Bl1 gibt es zwar größere Parameter, dafür allerdings nur bei Kanal 1 (chId = 0). Aufgefallen ist mir das Problem beim Testen eines "Homebrew"-Devices für 4 Rollo-Aktoren.
Mit Änderung des Ausdrucks in
$adrId       = $adrId + ($chId * $adressStep);
gibt es keine Probleme mehr. Ein paar Zeilen später taucht der Ausdruck nochmal in ähnlicher Form auf.

**Comment by ThorstenPferdekaemper** [comment]
So wie das Coding inzwischen aussieht wurde das bereits umgesetzt.
