### ISSUE TITLE
hm485d.pl auf remote computer?

### ISSUE THREAD

**Issue by MartinGoodwell** [kc-GitHub/FHEM-HM485#61]
Hallo,
ich möchte gern einen separaten Computer (zB RPi) nutzen, um hm485 über fhem anzusprechen.
den hm485d daemon kann ich prinzipiell starten, indem ich eine fhem instanz installiere, aber nicht starte, und dort drin dann direkt hm485d.pl mit den parametern ausführe.
Vergleichbar wäre dieser Ansatz zB mit owserver, der remote läuft und nur den 1-wire Bus ansteuert und von einer remote fhem-Instanz verwendet wird.

Auf meinem Haupt-FHEM kann ich auch das HM485 device anlegen, allerdings werden keine Devices (zB Aktoren) erkannt.

Zur Verifikation: wenn ich FHEM auf dem zweiten Computer ausführe, funktioniert das Erkennen der Devices ganz normal.

Würde mich über eine kurze Antwort freuen.

Danke
schöne Grüße
Martin

**Comment by ThorstenPferdekaemper** [comment]
Hi,
meiner Meinung nach müsste das im Prinzip funktionieren. Würde es Dir etwas ausmachen, das im FHEM-Forum im Homematic-Bereich zu diskutieren? Du kannst ja zu dem Issue hier Bezug nehmen. 
Wenn Du dort einen Thread aufmachst, dann könntest Du auch gleich ein "list" Deines HM485_LAN-Device machen sowie die genaue Command-Line wie Du den hm485d startest.
Gruß,
    Thorsten

**Comment by ThorstenPferdekaemper** [comment]
Ich habe das gerade mal spaßeshalber ausprobiert. Es hat funktioniert. Ich musste nur FHEM kurz durchstarten. Dann ging sogar discovery.
...aber wie gesagt: FHEM-Forum.

**Comment by MartinGoodwell** [comment]
Dank dir für die rasche Antwort.
Klar, ich werde einen Eintrag im Forum machen, sobald ich die Zeit finde.
Das es bei dir funktioniert hat, stimmt mich schon mal positiv :-)
