### ISSUE TITLE
EEPROM erhält falsche Werte, da conversion "to_device" nicht beachtet wird

### ISSUE THREAD

**Issue by loetmeister** [kc-GitHub/FHEM-HM485#64]
Die folgende Kanalkonfiguration schreibt `0x00` für` parameter_value="0"`, statt `0xFF`, bzw. `0x01` für `parameter_value="1"` statt `0x28`.
Es wird nur die `conversion` `value_map` `from_device="true"` und nicht `to_device="true"` beachtet.

Wenn die folgenden Zeilen in **ConfigurationManager.pm**, sub convertSettingsToEepromData auskommentiert werden, dann wird beim `logical type="option"` Elemente `to_device="true"` beachtet und die Werte werden sowohl beim lesen, als auch schreiben des EEPROM korrekt umgewandelt.
```
#	if ($configData->{$config}{'config'}{'logical'}{'type'} && 
#		$configData->{$config}{'config'}{'logical'}{'type'} eq 'option') {
#	} else {
		$value = HM485::Device::dataConversion(
			$value, $configData->{$config}{'config'}{'conversion'}, 'to_device'
		);
#	}
```

Device XML:
```
<parameter id="ONEWIRE_TYPE">
	<logical type="option">
		<option id="NOT_USED" default="true"/>
		<option id="DS18B20"/>
	</logical>
	<physical size="1.0" type="integer" interface="eeprom">
		<address index="+6.0"/>
	</physical>
	<conversion type="option_integer">
		<value_map to_device="true" from_device="true" parameter_value="0" device_value="0xFF"/>
		<value_map to_device="true" from_device="true" parameter_value="1" device_value="0x28"/>
	</conversion>
</parameter>
```

**Comment by ThorstenPferdekaemper** [comment]
Erledigt.
