### ISSUE TITLE
Speichern von "NOT_USED" in der Konfiguration nicht möglich

### ISSUE THREAD

**Issue by loetmeister** [kc-GitHub/FHEM-HM485#65]
`special_value id="NOT_USED"` scheint beim Speichern der Konfiguration nicht beachtet zu werden.
Anzeige der Konfiguration ist ok.

Wenn aber `NOT_USED` für `SEND_MAX_INTERVAL` gesetzt wird, dann scheint FHEM die geänderte Einstellung zu Speichern, im FHEM log erscheint aber:
_HBW_1W_T10_HBW7296278_03: Set config HBW_1W_T10_HBW7296278_03: **send_max_intervall=150**_
Gesetzt werden sollte aber send_max_intervall=0

XML:
```
<parameter id="SEND_MAX_INTERVAL">
	<logical type="integer" unit="s" default="150" min="5" max="3600">
		<special_value id="NOT_USED" value="0"/>
	</logical>
	<physical size="2.0" type="integer" interface="eeprom" endian="little">
		<address index="+4.0"/>
	</physical>
	<conversion type="integer_integer_map">
		<value_map to_device="false" from_device="true" parameter_value="150" device_value="0xffff"/>
	</conversion>
</parameter>
```

**Comment by loetmeister** [comment]
Ergänzung: Mit type="float" verhält es sich ebenfalls so. Es wird der "default" Wert genommen, statt special_value.

XML Beispiel:
(dort wird default="1.0", also 200 ins EEPROM geschrieben)
```
	<parameter id="SHORT_ON_LEVEL">
		<logical type="float" min="0.0" max="1.0" default="1.0" unit="100%">
			<special_value id="OLD_LEVEL" value="1.005"/>
		</logical>
		<conversion type="float_integer_scale" factor="200"/>
		<physical type="integer" size="1.0" interface="eeprom">
			<address index="+16"/>
		</physical>
	</parameter>
```

**Comment by ThorstenPferdekaemper** [comment]
Folgendes fehlt wahrscheinlich bzw. ist falsch:
1. In **hm485.js** wird überhaupt nur für Peerings der special_value-Eintrag beachtet. Es wird zwar die Checkbox etc. reingerendert, aber in FW_HM485ConfigSaveClicked fehlt es.
2. In **ConfigurationManager.pm**, Routine convertValueToDisplay werden keine special_value-Einträge beachtet. Dadurch zeigt das R-Reading möglicherweise nicht den special_value-Key an. (Vermutlich nur für float-Parameter, da hier eine Ausgabe-Formatierung versucht wird.)
3.  In **ConfigurationManager.pm**, Routine convertSettingsToEepromData müsste vor dem Aufruf von HM485::Device::dataConversion wahrscheinlich nach special_value geschaut werden. Analog zu configDataToAddressData in PeeringManager.pm. (Das dürfte der Hauptpunkt sein.)

**Comment by ThorstenPferdekaemper** [comment]
1 und 3 lokal bei mir geändert. Für den Test geht's jetzt im Forum weiter.

**Comment by ThorstenPferdekaemper** [comment]
Das sollte jetzt alles korrigiert sein.
